# safelist - only build on pushes to these branches
branches:
  only:
  - master
  - travis
# we needed this if wanted to build Hugo manually
# language: go
# go:
# - 1.10
install:
# change this version as it goes up
# get and install Hugo
- wget https://github.com/gohugoio/hugo/releases/download/v0.56.3/hugo_0.56.3_Linux-64bit.deb
- sudo dpkg -i hugo*.deb
# clone the parent repository, note this is different from Parsia-Clone
- git clone https://github.com/ErikBlomquist/korkenxyz-blog.git
- cd korkenxyz-blog
# update and fetch submodules
- git submodule init
- git submodule update --recursive --remote
script:
# build the website with Hugo, output will be in public directory
- hugo
# deploy public directory to the bucket
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: www.korken.xyz
  region: us-east-1
  local-dir: public
  skip_cleanup: true
  acl: public_read
  on:
    # make it work on branch other than master 
    # change this to master or any other branch if needed
    branch: master
