baseURL = "https://www.korken.xyz/"
languageCode = "en-us"
themesDir = "themes"
title = "KORKEN"
theme = "m10c"
paginate = 7
googleAnalytics = "UA-145070228-1"


[params]
  author = "Erik Blomquist"
  description = "Hello, I'm Erik Blomquist and this is a blog about my journey through the cloud."

[[params.social]]
  name = "github"
  url = "https://github.com/ErikBlomquist"

[[params.social]]
    name = "twitter"
    url = "https://www.twitter.com/koerk6"

[[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/erik-blomquist-0a7261173"


